HCLOUD_TOKEN: ENC[AES256_GCM,data:pXnBKLInyK2SsJPzVh1h1Ffk23FB1FYS1UhwkFHU5AziqxR/3jSAZut56XzS6jLlxIdT8vF/OJl0jZR5PswcnQ==,iv:Exhr6c3x+q++xqEJF5U09fYskMHyQpkPvm3MJXct3Yc=,tag:mQAnSX1YhzmlDouOB2/5DQ==,type:str]
TF_VAR_hcloud_token: ENC[AES256_GCM,data:vUShVgumzvPR3z1iqcivjinzI7bO4/g0OUYlOv5YWvufCuGODf/m5qt5sScW7Lz2LZJvhzBbihCEEoA3iqRUcQ==,iv:oiTmygs21XtYsCrxaAU6Lv4twsN0dJlz74yk0A+9vDc=,tag:3OnRbdVXnTsJt4//8ZFFMA==,type:str]
TF_VAR_github_token: ENC[AES256_GCM,data:1K/89XhoGlpz7290EjShMYguDVS1kqcV/vhfI8RfwQEhNERjCavLj9LYHHre71D1LYPaaKKSAJY2oBo++w918h7q0prsv6T4CXUA/AiRGSukxwYG6B5HTTkNYqP1,iv:pET1qO7Zx+7RGRN4vURvu9w7+sGhFNZxAwNnJyX6XY8=,tag:bjKqNK1Q3x+gM1IrpUjW3g==,type:str]
TF_VAR_state_passphrase: ENC[AES256_GCM,data:SCvqspEMqKA8oPsCnmFK59Cz5xD9S1fLtBxjdMlJA5s=,iv:Myuogzc/Uu5FDizz8djHbPI8C2u5vvttBUA1YC8u45E=,tag:iZj/9Kof1bMFoJPFl8VrFA==,type:str]
TF_VAR_b2_application_key: ENC[AES256_GCM,data:o9LzASyV0+L+QEJpomDNWOUkuK3JZysDM9zHd+vLt2WBo2cJA1B1rrSV,iv:GSTzNvD0VMfhG28uUUMu9ONQ1Br4rs662w0afrFB1UE=,tag:0o37QBEuF8RDgQpyegWYgQ==,type:str]
TF_VAR_b2_application_key_id: ENC[AES256_GCM,data:U8qkwfXejbrGR+4X,iv:dBTsrJmLI3v0RPTzBZKrYJNHn1bilQYiWHumuajGro8=,tag:s0AqkQiVPq4ExhoOxfhing==,type:str]
sops:
    age:
        - recipient: age17p4sqz4vf27nsn0fgsqacg26pxpegdy0l4hpp099pt09hz996dqs6lped7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFVhU0hhTHJlZUVnYkp1
            MkxMbGNZd1gvYlF1c2ZOUlF1U21IUHE2MjBBClZjdDNNTk90THd0SzVWNmtGdnlx
            ek1XVEJzVytrZ0FRZ3lManV1QVZpWFkKLS0tIFZJRGhXL2dEVkRhTGJTdFZXZXFW
            VVVaYTBEcGM2TmxtUWg3SFo5cGFuSHcKfqb6iXfW6xdu3kJEaiRR4MmSFY+NuApq
            uI3F3IWa0DnPTpSiH7UiBkPWYFz63NgnsaFes3nsXbtaIQpIuVkAsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T19:42:45Z"
    mac: ENC[AES256_GCM,data:CXXjy0pc4lq8ZgxBBarGYB7l1hV4/3wviwh5bgxd1Jq2OK3HGqc69Fi9N4J3JfKYhCR8Z0Kw3HPVCHgcJ5gB4D+X8r+5GOutVlJFe9t11Epci0zz3XPqbobnYZdLOXP8zJjHfCZNeNOWeZuFtIl4R4/mDCZwEB6LlUJ9Y0NMV3U=,iv:AkzROQyH9KXSYxWkYUEeSNSuFk6bT/snf4TzXZL5AsE=,tag:9UmylZrCXNrY9HTEu6cE+Q==,type:str]
    unencrypted_regex: ^(metadata|kind|apiVersion)$
    version: 3.11.0
