HCLOUD_TOKEN: ENC[AES256_GCM,data:pXnBKLInyK2SsJPzVh1h1Ffk23FB1FYS1UhwkFHU5AziqxR/3jSAZut56XzS6jLlxIdT8vF/OJl0jZR5PswcnQ==,iv:Exhr6c3x+q++xqEJF5U09fYskMHyQpkPvm3MJXct3Yc=,tag:mQAnSX1YhzmlDouOB2/5DQ==,type:str]
TF_VAR_hcloud_token: ENC[AES256_GCM,data:vUShVgumzvPR3z1iqcivjinzI7bO4/g0OUYlOv5YWvufCuGODf/m5qt5sScW7Lz2LZJvhzBbihCEEoA3iqRUcQ==,iv:oiTmygs21XtYsCrxaAU6Lv4twsN0dJlz74yk0A+9vDc=,tag:3OnRbdVXnTsJt4//8ZFFMA==,type:str]
TF_VAR_github_token: ENC[AES256_GCM,data:1K/89XhoGlpz7290EjShMYguDVS1kqcV/vhfI8RfwQEhNERjCavLj9LYHHre71D1LYPaaKKSAJY2oBo++w918h7q0prsv6T4CXUA/AiRGSukxwYG6B5HTTkNYqP1,iv:pET1qO7Zx+7RGRN4vURvu9w7+sGhFNZxAwNnJyX6XY8=,tag:bjKqNK1Q3x+gM1IrpUjW3g==,type:str]
sops:
    age:
        - recipient: age17p4sqz4vf27nsn0fgsqacg26pxpegdy0l4hpp099pt09hz996dqs6lped7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFVhU0hhTHJlZUVnYkp1
            MkxMbGNZd1gvYlF1c2ZOUlF1U21IUHE2MjBBClZjdDNNTk90THd0SzVWNmtGdnlx
            ek1XVEJzVytrZ0FRZ3lManV1QVZpWFkKLS0tIFZJRGhXL2dEVkRhTGJTdFZXZXFW
            VVVaYTBEcGM2TmxtUWg3SFo5cGFuSHcKfqb6iXfW6xdu3kJEaiRR4MmSFY+NuApq
            uI3F3IWa0DnPTpSiH7UiBkPWYFz63NgnsaFes3nsXbtaIQpIuVkAsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T05:08:37Z"
    mac: ENC[AES256_GCM,data:gV6fSshvNCGAaKZOxAJiLMM3CFE42szkJYVTxPqCYChfFA5k6Wu3mM0UDHF3KtizVGxJBMxlZoEGARklBSqd1AipBgHPvGukYBXw/MIGeWUp12UtwitHwrNToBzP3Dzb8+I64BJQJlgb0nNh/yzA0t6xkNXXxkCEF/5m+4I6LCg=,iv:1LtZhFddZczdCIferbjYkP4nLInRg5LEH2D0tBamJA4=,tag:G1Nvs8DA/f/KnUgUm5u9Mg==,type:str]
    unencrypted_regex: ^(metadata|kind|apiVersion)$
    version: 3.11.0
